### ISSUE TITLE
TypeError: fastify.next is not a function after npm run dev

### ISSUE THREAD

**Issue by iaomar** [typedef42/nextjs-fastify-i18n#2]
Hi! I followed your quick recap of how to init and run this repos from medium and get error while **npm run dev**:

```
PS D:\Projects\nextjs-fastify-i18n> npm run dev

> nextjs-fastify-i18n@1.0.0 dev D:\Projects\nextjs-fastify-i18n
> cross-env NODE_ENV=development node server.js

D:\Projects\nextjs-fastify-i18n\server.js:30
    fastify.next("/");
            ^

TypeError: fastify.next is not a function
    at D:\Projects\nextjs-fastify-i18n\server.js:30:13
    at Object._encapsulateThreeParam (D:\Projects\nextjs-fastify-i18n\node_modules\avvio\boot.js:399:13)
    at Boot.callWithCbOrNextTick (D:\Projects\nextjs-fastify-i18n\node_modules\avvio\boot.js:339:5)
    ...
```

Do you have any ideas what this problem is and how to solve it? Thanks

**Comment by typedef42** [comment]
Hi @iaomar,

I'm pretty sure it's because of the async loading time of the next plugin in fastify.
by default, fastify has a 10sec or so timeout, and at first build next can take more than this threshold to start. That makes fastify throw a timeout error, and then does not load the plugin, so the .next() function is not attached to the fastify context.

You can fix it by increasing the plugin timeout loading time, even though it would be better to have some loading callback mechanism in the plugin.

```js
const fastify = require("fastify")({
  pluginTimeout: 35000,
  http2: true,
  https: {
    key: fs.readFileSync(path.join(__dirname, "certs/privateKey.key")),
    cert: fs.readFileSync(path.join(__dirname, "certs/certificate.crt"))
  }
});
```

**Comment by iaomar** [comment]
> Hi @iaomar,
> 
> I'm pretty sure it's because of the async loading time of the next plugin in fastify.
> by default, fastify has a 10sec or so timeout, and at first build next can take more than this threshold to start. That makes fastify throw a timeout error, and then does not load the plugin, so the .next() function is not attached to the fastify context.
> 
> You can fix it by increasing the plugin timeout loading time, even though it would be better to have some loading callback mechanism in the plugin.
> 
> ```js
> const fastify = require("fastify")({
>   pluginTimeout: 35000,
>   http2: true,
>   https: {
>     key: fs.readFileSync(path.join(__dirname, "certs/privateKey.key")),
>     cert: fs.readFileSync(path.join(__dirname, "certs/certificate.crt"))
>   }
> });
> ```

That helped. Thank you very much for your work!
