### ISSUE TITLE
localhost didn’t send any data.

### ISSUE THREAD

**Issue by lamualfa** [typedef42/nextjs-fastify-i18n#3]
The server does not respond to any data when I access localhost:5000/

![image](https://user-images.githubusercontent.com/39755201/73646061-36257d80-46ab-11ea-8897-1b85f8b1bed3.png)

**Comment by typedef42** [comment]
Hi @laodemalfatih, 

Are you sure nothing is blocking your localhost ports (firewall, av...).
I can't reproduce your problem
